-- Seed tbl_partner từ export BookingCare / file tbl_partner (1).csv
-- CareNow chỉ nhận các cột form/API: bỏ sync_status, phone, metadata nội bộ BC (gom gọn vào note nếu cần).
-- Chạy: psql -U postgres -d CareNow -f src/config/migrations/2026_05_08_seed_partner_from_tbl_partner_csv.sql
--
-- Idempotency: UPSERT theo PRIMARY KEY id.

BEGIN;

INSERT INTO tbl_partner (
  id,
  name,
  short_name,
  description,
  address,
  status,
  created_time,
  updated_time,
  "group",
  license,
  rank,
  email,
  payment_method,
  booking_fee,
  payment_scope,
  features,
  documents,
  note
) VALUES
(
  3,
  'Bệnh viện An Việt',
  'BV An Việt',
  NULL,
  '1E Trường Chinh - Thanh Xuân - HN',
  1,
  1456765200,
  1773410537,
  1,
  'Giấy phép hoạt động khám bệnh, chữa bệnh số: 187/BYT-GPHD, cấp ngày 04/02/2016',
  4,
  NULL,
  0,
  0,
  0,
  '["full_birthday","new_location"]'::jsonb,
  '[]'::jsonb,
  'Nguồn: tbl_partner (1).csv | drive_folder_id (legacy): 13Nk8epkSDx76TeEdnxFvYwku6Pvs4J33'
),
(
  4,
  'Bệnh viện Đông Đô',
  'BV Đông Đô',
  NULL,
  'Số 5 Xã Đàn - Đống Đa - HN',
  1,
  1456765200,
  1760930014,
  1,
  'Giấy phép hoạt động khám bệnh, chữa bệnh số: 49/BYT-GPHD, cấp ngày 05/05/2015',
  21,
  NULL,
  0,
  0,
  0,
  '["datlich_appointment_reason","datlich_payment_bank_disabled","datlich_payment_momo_disabled","datlich_payment_nganluong_disabled"]'::jsonb,
  '[]'::jsonb,
  'Nguồn: tbl_partner (1).csv | drive_folder_id (legacy): 1Zpf9Rmw9LO6yi1G59vZrNLcWA6DGAgV8'
),
(
  49,
  'Hệ thống Y tế Thu Cúc',
  'HT Thu Cúc',
  NULL,
  'CS1: 286 Thụy Khuê, Tây Hồ, Hà Nội;  CS2: 216 Trần Duy Hưng, Cầu Giấy, Hà Nội;  CS3: 32 Đại Từ, Hoàng Mai, Hà Nội',
  1,
  1517571493,
  1765868498,
  2,
  NULL,
  8,
  NULL,
  0,
  0,
  0,
  '["full_birthday","new_location","datlich_appointment_reason"]'::jsonb,
  '[]'::jsonb,
  E'Bệnh viện sẽ chủ động liên hệ, nhắc đối tác check bệnh nhân hoặc ca gấp liên hệ tổng đài bệnh viện: 0985887755 báo bên BookingCare đặt lịch.\nNguồn: tbl_partner (1).csv | drive_folder_id (legacy): 1fo8pDUVvZMvhsfiMGeCW933sg1VUOCg3'
),
(
  80,
  'Bệnh viện Y học cổ truyền Trung ương',
  'BV YHCT TW',
  NULL,
  '29 Nguyễn Bỉnh Khiêm, Hà Nội',
  1,
  1529899184,
  1777087603,
  1,
  NULL,
  19,
  NULL,
  0,
  0,
  0,
  NULL,
  '[]'::jsonb,
  'Nguồn: tbl_partner (1).csv | drive_folder_id (legacy): 1OwZXmtLtO8LQ7tdZQqsjtGIBHxXTIoNr'
),
(
  89,
  'Bệnh viện Bệnh Nhiệt đới Trung ương',
  'BV Bệnh Nhiệt đới',
  NULL,
  'Số 78, đường Giải Phóng, Hà Nội',
  1,
  1535471673,
  1777087603,
  1,
  NULL,
  999999,
  NULL,
  0,
  0,
  0,
  '["full_address","full_birthday","new_location","datlich_cccd_enabled","datlich_cccd_issue_date_enabled"]'::jsonb,
  '[]'::jsonb,
  'Nguồn: tbl_partner (1).csv | drive_folder_id (legacy): 1u2x_7tTGwTGVt696Lvu1Mjdi1_ZYTi1b'
),
(
  107,
  'Bệnh viện Ung bướu Hưng Việt',
  'BV UB Hưng Việt',
  NULL,
  '34 Đại Cồ Việt, Hai Bà Trưng, Hà Nội',
  1,
  1581300801,
  1772418586,
  2,
  'Giấy phép hoạt động khám bệnh, chữa bệnh số 29/BYT-GPHĐ cấp ngày 29/01/2013',
  12,
  NULL,
  0,
  0,
  0,
  '["full_address","full_birthday","dms_appointment_sharing"]'::jsonb,
  '[]'::jsonb,
  'Nguồn: tbl_partner (1).csv | drive_folder_id (legacy): 1pgNuLi9HOT0VPgZK51xHTePohyxcwoe5'
),
(
  378,
  'Hệ thống y tế MEDLATEC',
  'Hệ thống MEDLATEC',
  NULL,
  '42 Nghĩa Dũng, Phúc xá, Ba Đình, Hà Nội',
  1,
  1665717212,
  1764317534,
  2,
  NULL,
  99,
  NULL,
  1,
  0,
  0,
  '["full_address","full_birthday","datlich_custom_location","datlich_appointment_reason"]'::jsonb,
  '[]'::jsonb,
  'Nguồn: tbl_partner (1).csv | CSV rank trống → đặt 99. | drive_folder_id (legacy): 1Bl2_I6AQDL9GQYUyBA3MgxX7o02__2OV'
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  short_name = EXCLUDED.short_name,
  description = EXCLUDED.description,
  address = EXCLUDED.address,
  status = EXCLUDED.status,
  created_time = EXCLUDED.created_time,
  updated_time = EXCLUDED.updated_time,
  "group" = EXCLUDED."group",
  license = EXCLUDED.license,
  rank = EXCLUDED.rank,
  email = EXCLUDED.email,
  payment_method = EXCLUDED.payment_method,
  booking_fee = EXCLUDED.booking_fee,
  payment_scope = EXCLUDED.payment_scope,
  features = EXCLUDED.features,
  documents = EXCLUDED.documents,
  note = EXCLUDED.note;

COMMIT;
